swagger: '2.0'

info:
  version: "0.0.1"
  title: API de catálogos.
  description:
    API para consulta de catálogos del proceso originación de crédito - préstamos personales (clientes nuevos).

host: 
  dev-apigee-alb01-133938325.us-east-1.elb.amazonaws.com

basePath: /cobranza_credito/originacion/catalogos/v1

schemes:
  - http
  - https

produces:
  - application/json

securityDefinitions:
  Bearer:
    description: >
      Para acceder a la API se debe pasar un token válido en todas las consultas.
      La siguiente sintaxis se debe utilizar en el encabezado 'Authorization':
        Bearer:  2zzLJmBAtTNIU8nF8e8XbmDvaNGs
    type: apiKey
    name: Authorization
    in: header

security:
  - Bearer: []

paths:
  
  /motivos_credito:
    get:
      description:
        Motivo  de la petición de un préstamo.
      tags:
        -  Motivos de Crédito.
      produces: 
        - application/json 
      responses: 
        200:
          description: Ok.
          schema:
            $ref: '#/definitions/respuestaMotivosCredito'
          examples:
            application/json: |-
                {
                  "codigo": 100200,
                  "mensaje": "Operación exitosa.",
                  "folio": "100-201906031103383463",
                  "resultado": {
                    "motivos": [
                      {
                        "id": 1,
                        "descripcion": "Emergencia"
                      },
                      {
                        "id": 2,
                        "descripcion": "Liquidación de otras deudas"
                      },
                      {
                        "id": 3,
                        "descripcion": "Remodelación/Construcción"
                      },
                      {
                        "id": 4,
                        "descripcion": "Evento Social Familiar"
                      },
                      {
                        "id": 5,
                        "descripcion": "Gastos"
                      }
                    ]
                  }
                }            
                
                


        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.140400",
                "mensaje": "No encontrado.",
                "folio": "404-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140400",
                "detalles": [
                  ""
                ]
              }

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json: |-                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.150000",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "500-201905281852525176",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150000",
                  "detalles": [
                    ""
                  ]
                }

      security:
       - Bearer: []
       
  /destinos_credito:
    get:
      description:
        Destino de la petición de un préstamo.
      tags:
        -  Motivos de Crédito.
      produces: 
        - application/json        
      parameters:
      - name: "idMotivo"
        in: "query"
        description: "Motivo"
        required: true
        type: "integer"
        format: "int64"

      responses: 
        200:
          description: Ok.
          schema:
            $ref: '#/definitions/respuestaDestinosCredito'
          examples: 
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "100-201905281852525176",
                "resultado": {
                  "destinos": [
                    {
                      "id": 1,
                      "descripcion": "Accidentes"
                    },
                    {
                      "id": 2,
                      "descripcion": "Enfermedades"
                    },
                    {
                      "id": 3,
                      "descripcion": "Gastos Funerarios"
                    }
                  ]
                }
              }
                    
        400:
          description: Solicitud inválida.
          schema:
            $ref: '#/definitions/error'              
          examples:
            application/json: |-
              {
                "codigo": "400.CobranzaCredito-Catalogos.140000",
                "mensaje": "Parámetros no validos.",
                "folio": "400-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#400.CobranzaCredito-Catalogos.140000",
                "detalles": [
                  ""
                ]
              }
          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.140400",
                "mensaje": "No encontrado.",
                "folio": "404-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140400",
                "detalles": [
                  ""
                ]
              }

        500:
            description:  Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json: |-                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.150000",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "500-201905281852525176",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150000",
                  "detalles": [
                    ""
                  ]
                }
                
      security:
       - Bearer: []        
  
  /tipos_identificacion:
    get:
      description: Realiza la consulta de tipo de identificación del cliente.
      tags:
        - Identificaciones.
      produces: 
        - application/json
      responses: 
        200:
          description: Ok.
          schema:
            $ref: '#/definitions/respuestaIdentificacion'
          examples: 
            application/json: |-
              {
                "codigo": 100100,
                "mensaje": "Operación exitosa.",
                "folio": "101-060520191915062004",
                "resultado": {
                  "identificaciones": [
                    {
                      "id": "1",
                      "descripcion": "INE"
                    },
                    {
                      "id": "2",
                      "descripcion": "Pasaporte"
                    },
                    {
                      "id": "3",
                      "descripcion": "NA"
                    }
                  ]
                }
              }

        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.101404",
                "mensaje": "No encontrado.",
                "folio": "101-080520191915062478",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.1404"
              }     

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json: |-                               
                {
                  "codigo": "500.CobranzaCredito-Catalogos.101500",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "101-080520191915062485",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.1500",
                }
                
      security:
       - Bearer: []

  /dias_pago:
    get:
      description: Realiza la consulta del catálogo de días de pago.
      tags:
        - Días de pago.
      produces: 
        - application/json

      responses: 
        200:
          description: Ok.
          schema:
            $ref: '#/definitions/respuestaDiasPagos'
          examples: 
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "100-201906031103383463",
                "resultado": {
                  "dias": [
                    {
                      "id":  1,
                      "descripcion": "Lunes"
                    },
                    {
                      "id": 2,
                      "descripcion": "Martes"
                    },
                    {
                      "id": 3,
                      "descripcion": "Miercoles"
                    },
                    {
                      "id": 4,
                      "descripcion": "Jueves"
                    },
                    {
                      "id": 5,
                      "descripcion": "Viernes"
                    },
                    {
                      "id": 6,
                      "descripcion": "Sabado"
                    },
                    {
                      "id": 7,
                      "descripcion": "Domingo"
                    }
                  ]
                }
              }
          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.100404",
                "mensaje": "No encontrado.",
                "folio": "100-201906031103383463",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.100404",
                "detalles": [
                  ""
                ]
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json: |-                         
                {
                  "codigo": "500.CobranzaCredito-Catalogos.100500",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "100-201906031103383463",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.100500",
                  "detalles": [
                    ""
                  ]
                }
                
      security:
       - Bearer: []

  /tipos_dispersion: 
    get:
      description:
        Consulta las diferentes opciones  de dispersión.
      tags:
        - Tipos de dispersión.      
      produces: 
        - application/json
    
      responses: 
        200:
          description:  Ok.
          schema:
            $ref: '#/definitions/respuestaTiposDispersion'
          examples: 
            application/json: |-
              {
                "codigo": "100102",
                "mensaje": "Operación exitosa.",
                "folio": "101-090520191915062410",
                "resultado": {
                  "dispersiones": [
                    {
                      "id": "1",
                      "descripcion": "Tarjeta"
                    },
                    {
                      "id": "2",
                      "descripcion": "Tarjeta azteca"
                    },
                    {
                      "id": "3",
                      "descripcion": "Guardadito"
                    },
                    {
                      "id": "4",
                      "descripcion": "Efectivo"
                    }
                  ]
                }
              }

          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              {
                "codigo": "404.CobranzaCredito-Catalogos.140410",
                "mensaje": "No encontrado.",
                "folio": "101-090520191915062410",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140410"
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.150010",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "101-090520191915062410",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150010"
                }
      
      security:
       - Bearer: []

  /generos: 
    get:
      description:
        Consulta el catálogo de géneros.
      tags:
        - Géneros.      
      produces: 
        - application/json
    
      responses: 
        200:
          description:  Ok.
          schema:
            $ref: '#/definitions/respuestaGeneros'
          examples: 
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "100-201905281852525176",
                "resultado": {
                  "generos": [
                    {
                      "id": 1,
                      "descripcion": "Mujer"
                    },
                    {
                      "id": 2,
                      "descripcion": "Hombre"
                    }
                  ]
                }
              }

          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              {
                "codigo": "404.CobranzaCredito-Catalogos.100404",
                "mensaje": "No encontrado.",
                "folio": "100-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.100404",
                "detalles": [
                  ""
                ]
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.100500",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "100-201905281852525176",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.100500",
                  "detalles": [
                    ""
                  ]
                }
      
      security:
       - Bearer: []

  /estado_civil: 
    get:
      description:
        Consulta el catálogo de estado civil.
      tags:
        - Estado civil.      
      produces: 
        - application/json
    
      responses: 
        200:
          description:  Ok.
          schema:
            $ref: '#/definitions/respuestaEstadoCivil'
          examples: 
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "100-201905281852525176",
                "resultado": {
                  "estadoCivil": [
                    {
                      "id": 1,
                      "descripcion": "Soltero(a)"
                    },
                    {
                      "id": 2,
                      "descripcion": "Casado(a)"
                    },
                    {
                      "id": 3,
                      "descripcion": "Divorciado(a)"
                    },
                    {
                      "id": 4,
                      "descripcion": "Unión libre"
                    },
                    {
                      "id": 5,
                      "descripcion": "Viudo(a)"
                    }
                  ]
                }
              }

          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              {
                "codigo": "404.CobranzaCredito-Catalogos.100404",
                "mensaje": "No encontrado.",
                "folio": "100-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.100404",
                "detalles": [
                  ""
                ]
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.100500",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "100-201905281852525176",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.100500",
                  "detalles": [
                    ""
                  ]
                }
      
      security:
       - Bearer: []
       
  /creditos/productos:
    get:
      description:
        Consulta el catálogo de los diferentes productos.
      tags:
        - Productos.      
      produces: 
        - application/json
    
      responses: 
        200:
          description:  Ok.
          schema:
            $ref: '#/definitions/respuestaProductos'
          examples: 
            application/json: |-
              {
                "codigo": "100200",
                "mensaje": "Operación exitosa.",
                "folio": "100-201906031103383463",
                "resultado": {
                    "productos": [
                        {
                            "id": "1",
                            "descripcion": "Préstamos Personales."
                        },
                        {
                            "id": "2",
                            "descripcion": "Big."
                        },
                        {
                            "id": "3",
                            "descripcion": "Modatelas."
                        },
                        {
                            "id": "4",
                            "descripcion": "Tarjetas de crédito Oro."
                        },
                        {
                            "id": "5",
                            "descripcion": "Waldo's."
                        },
                        {
                            "id": "6",
                            "descripcion": "Captación en Baz Digital."
                        },
                        {
                            "id": "7",
                            "descripcion": "Consumo."
                        },
                        {
                            "id": "8",
                            "descripcion": "Italika."
                        },
                        {
                            "id": "9",
                            "descripcion": "Telefonía."
                        },
                        {
                            "id": "10",
                            "descripcion": "Préstamos."
                        },
                        {
                            "id": "11",
                            "descripcion": "Préstamos empleado."
                        },
                        {
                            "id": "12",
                            "descripcion": "Tarjeta Azteca."
                        },
                        {
                            "id": "13",
                            "descripcion": "Tarjeta Escuela de Clientes."
                        },
                        {
                            "id": "14",
                            "descripcion": "Tarjeta de Crédito Elektra."
                        },
                        {
                            "id": "15",
                            "descripcion": "Adelanto de nómina."
                        }
                    ]
                }
              }

          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              {
                "codigo": "404.CobranzaCredito-Catalogos.140410",
                "mensaje": "No encontrado.",
                "folio": "100-0905201919150624",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140410",
                "detalles": [
                  ""
                ]
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.150010",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "100-0905201919150624",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150010",
                  "detalles": [
                    ""
                  ]
                }
      
      security:
       - Bearer: []


  /tipos_empleo:
    get:
      description:
        Consulta el catálogo de los diferentes Tipos de Empleo.
      tags:
        - Tipos de Empleo.      
      produces: 
        - application/json
    
      responses: 
        200:
          description:  Ok.
          schema:
            $ref: '#/definitions/respuestaTiposEmpleo'
          examples: 
            application/json: |-
                 {
                      "codigo": 100200,
                      "mensaje": "Operación exitosa.",
                      "folio": "100-201906031103383463",
                      "resultado": {
                        "empleos": [
                          {
                            "id": 1,
                            "descripcion": "EMPLEADO"
                          },
                          {
                            "id": 2,
                            "descripcion": "SOCIO/PROPIETARIO"
                          },
                          {
                            "id": 3,
                            "descripcion": "PENSIONADO"
                          },
                          {
                            "id": 4,
                            "descripcion": "POR SU CUENTA"
                          },
                          {
                            "id": 5,
                            "descripcion": "AMA DE CASA"
                          },
                          {
                            "id": 6,
                            "descripcion": "BECADO"
                          },
                          {
                            "id": 7,
                            "descripcion": "ESTUDIANTE"
                          }
                        ]
                      }
                    }
          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              {
                "codigo": "404.CobranzaCredito-Catalogos.140410",
                "mensaje": "No encontrado.",
                "folio": "100-0905201919150624",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140410",
                "detalles": [
                  ""
                ]
              } 

        500:
            description: Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.150010",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "100-0905201919150624",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150010",
                  "detalles": [
                    ""
                  ]
                }
      
      security:
       - Bearer: []
       
  /ocupaciones:
      get:
        description:
          Consulta el catálogo de las diferentes Ocupaciones.
        tags:
          - Ocupaciones.      
        produces: 
          - application/json
      
        responses: 
          200:
            description:  Ok.
            schema:
              $ref: '#/definitions/respuestaOcupaciones'
            examples: 
              application/json: |-
                  {
                    "codigo": 100200,
                    "mensaje": "Operación exitosa.",
                    "folio": "100-201906031103383463",
                    "resultado": {
                      "ocupaciones": [
                        {
                          "id": 1,
                          "descripcion": "ABARROTERO"
                        },
                        {
                          "id": 2,
                          "descripcion": "ABOGADO"
                        },
                        {
                          "id": 3,
                          "descripcion": "ADMINISTRADOR"
                        },
                        {
                          "id": 4,
                          "descripcion": "AGRICULTOR"
                        },
                        {
                          "id": 5,
                          "descripcion": "ALBAÑIL"
                        }
                      ]
                    }
                  }
                          
          404:
            description: Recurso no encontrado.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json:
                {
                  "codigo": "404.CobranzaCredito-Catalogos.140410",
                  "mensaje": "No encontrado.",
                  "folio": "100-0905201919150624",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140410",
                  "detalles": [
                    ""
                  ]
                } 

          500:
              description: Error interno en el servidor.
              schema:
                $ref: '#/definitions/error'
              examples:
                application/json:                                
                  {
                    "codigo": "500.CobranzaCredito-Catalogos.150010",
                    "mensaje": "No se recibió respuesta del servidor.",
                    "folio": "100-0905201919150624",
                    "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.150010",
                    "detalles": [
                      ""
                    ]
                  }
        
        security:
        - Bearer: []

  /paises:
    get:
      description: Realiza de los paises disponibles para crédito personal.
      tags:
        - Paises.
      produces:
       - application/json
      responses:
        200:
          description: Ok.
          schema: 
            $ref: '#/definitions/respuestaPais'
          examples:
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "101-060520191915062004",
                "resultado": {
                  "paises": {
                    "id": "1",
                    "descripcion": "México"
                  }
                }
              }

        
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.140400",
                "mensaje": "No encontrado.",
                "folio": "404-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140400"
              }
          

        500:
          description: Error interno en el servidor.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.140400",
                "mensaje": "No encontrado.",
                "folio": "404-201905281852525176",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.140400"
              }
         
        
      security:
      - Bearer: []

  /municipios:
    get:
      description: Consulta de municipios por estado.
      tags:
        -  Municipios.
      produces: 
        - application/json        
      parameters:
      - name: idEstado
        in: query
        description: Id del estado del que se consultaran los municipios.
        required: true
        type: integer
        format: int64

      responses: 
        200:
          description: Ok.
          schema:
            $ref: '#/definitions/respuestaMunicipios'
          examples: 
            application/json: |-
              {
                "codigo": 100200,
                "mensaje": "Operación exitosa.",
                "folio": "100-201905281852525777",
                "resultado": {
                  "municipios": [
                    {
                      "id": 1,
                      "descripcion": "Álvaro Obregón"
                    },
                    {
                      "id": 2,
                      "descripcion": "Azcapotzalco"
                    },
                    {
                      "id": 3,
                      "descripcion": "Benito Juárez"
                    },
                    {
                      "id": 4,
                      "descripcion": "Coyoacán"
                    },
                    {
                      "id": 5,
                      "descripcion": "Cuajimalpa de Morelos"
                    },
                    {
                      "id": 6,
                      "descripcion": "Cuauhtémoc"
                    },
                    {
                      "id": 7,
                      "descripcion": "Gustavo A. Madero"
                    },
                    {
                      "id": 8,
                      "descripcion": "Iztacalco"
                    },
                    {
                      "id": 9,
                      "descripcion": "Iztapalapa"
                    },
                    {
                      "id": 10,
                      "descripcion": "La Magdalena Contreras"
                    },
                    {
                      "id": 11,
                      "descripcion": "Miguel Hidalgo"
                    },
                    {
                      "id": 12,
                      "descripcion": "Milpa Alta"
                    },
                    {
                      "id": 13,
                      "descripcion": "Tlalpan"
                    },
                    {
                      "id": 14,
                      "descripcion": "Tláhuac"
                    },
                    {
                      "id": 15,
                      "descripcion": "Venustiano Carranza"
                    },
                    {
                      "id": 16,
                      "descripcion": "Xochimilco"
                    }
                  ]
                }
              }
                    
        400:
          description: Solicitud inválida.
          schema:
            $ref: '#/definitions/error'              
          examples:
            application/json: |-
              {
                "codigo": "400.CobranzaCredito-Catalogos.100400",
                "mensaje": "Parámetros no validos.",
                "folio": "400-201905281852525777",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#400.CobranzaCredito-Catalogos.100400",
                "detalles": [
                  ""
                ]
              }
          
        404:
          description: Recurso no encontrado.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.CobranzaCredito-Catalogos.100404",
                "mensaje": "No encontrado.",
                "folio": "404-201905281852525777",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-Catalogos.100404",
                "detalles": [
                  ""
                ]
              }

        500:
            description:  Error interno en el servidor.
            schema:
              $ref: '#/definitions/error'
            examples:
              application/json: |-                                
                {
                  "codigo": "500.CobranzaCredito-Catalogos.100500",
                  "mensaje": "No se recibió respuesta del servidor.",
                  "folio": "500-201905281852525777",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-Catalogos.100500",
                  "detalles": [
                    ""
                  ]
                }
                
      security:
       - Bearer: []

definitions:
  
  respuestaMotivosCredito:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "MotivosCrédito - Consulta exitosa"
      folio:
        type: string
        description: Folio de la operación.
        example: "22920181228093345466"
      resultado:
        type: object
        properties:
          motivos:
            $ref: '#/definitions/motivos'

  motivos:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "Emergencia"
              
  respuestaDestinosCredito:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "MotivosCrédito - Consulta exitosa"
      folio:
        type: string
        description: Folio de la operación.
        example: "22920181228093345466"
      resultado:
        type: object
        properties:
          destinos:
            $ref: '#/definitions/destinos'
  
  destinos:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "Accidentes"
   
  respuestaIdentificacion:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación
        example: "Tipo de Identificación - Consulta exitosa"
      folio:
        type: string
        description: Folio de la operación 
        example: "22920181228093345466"
      resultado:
        type: object
        properties:
          identificaciones:
            $ref: '#/definitions/identificaciones'
  
  identificaciones:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "INE"

  respuestaDiasPagos:
    type: object
    properties:
      codigo:
        type: integer
        description: Código de operación.
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Operación exitosa."
      folio:
        type: string
        description: Folio de la operación.
        example: "100-201906031103383463"
      resultado:
        type: object
        properties:
          dias:
            $ref: '#/definitions/dias'
  
  dias:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "Lunes"

  respuestaTiposDispersion:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Todo se ha procesado correctamente."
      folio:
        type: string
        description: Folio de la operación.
        example: "CE-0905201919150624"
      resultado:
        type: object
        properties:
          dispersiones:
            $ref: '#/definitions/dispersiones'

  dispersiones:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "Tarjeta"
  
  respuestaGeneros:
    type: object
    properties:
      codigo:
        type: integer
        description: Código de operación.
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Operación exitosa."
      folio:
        type: string
        description: Folio de la operación.
        example: "100-201905281852525176"
      resultado:
        type: array
        items:
           $ref: "#/definitions/generos"
        example:
          - id: 1
            descripcion: "Mujer"
          - id: 2
            descripcion: "Hombre"

  generos:
    type: object
    properties:
      id:
        type: integer
        description: Id del género.
      descripcion:
        type: string
        description: Descripción del objeto género.

  respuestaEstadoCivil:
    type: object
    properties:
      codigo:
        type: integer
        description: Código de operación.
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Operación exitosa."
      folio:
        type: string
        description: Folio de la operación.
        example: "100-201905281852525176"
      resultado:
        type: array
        items:
           $ref: "#/definitions/estadoCivil"
        example:
          - id: 1
            descripcion: "Soltero(a)"
          - id: 2
            descripcion: "Casado(a)"
          - id: 3
            descripcion: "Divorciado(a)"
          - id: 4
            descripcion: "Unión libre"
          - id: 5
            descripcion: "Viudo(a)"

  estadoCivil:
    type: object
    properties:
      id:
        type: integer
        description: Id del estado civil.
      descripcion:
        type: string
        description: Descripción del objeto estado civil.

  respuestaProductos:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Todo se ha procesado correctamente."
      folio:
        type: string
        description: Folio de la operación.
        example: "CE-0905201919150624"
      resultado:
        type: object
        properties:
          dispersiones:
            $ref: '#/definitions/productos'
  
  productos:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "Préstamos Personales."

  respuestaTiposEmpleo:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación
        example: "Consulta exitosa"
      folio:
        type: string
        description: Folio de la operación 
        example: "100-201906031103383463"
      resultado:
        type: object
        properties:
          empleos:
            $ref: '#/definitions/tiposEmpleos'
  
  tiposEmpleos:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "EMPLEADO"
            
  respuestaOcupaciones:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación
        example: "Consulta exitosa"
      folio:
        type: string
        description: Folio de la operación 
        example: "100-201906031103383463"
      resultado:
        type: object
        properties:
          ocupaciones:
            $ref: '#/definitions/ocupaciones'
  
  ocupaciones:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          descripcion:
            type: string
            example: "ABARROTERO"            

  respuestaPais:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: "2"
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Todo se ha procesado correctamente."
      folio:
        type: string
        description: Folio de la operación.
        example: "101-060520191915062004"
      resultado: 
        type: object
        properties:
          dispersiones:
            $ref: '#/definitions/pais'
      
  pais:
    type: object
    items:
      type: object
      properties:
        id:
          type: integer
          example: 1
        descripcion:
          type: string
          example: "México"


  respuestaMunicipios:
    type: object
    properties:
      codigo:
        type: string
        description: Código de operación.
        example: 100200
      mensaje:
        type: string
        description: Descripción de la operación.
        example: "Operación exitosa."
      folio:
        type: string
        description: Folio de la operación.
        example: "100-201905281852525777"
      resultado:
        type: array
        items:
           $ref: "#/definitions/municipios"
        example:
          - id: 1
            descripcion: "Álvaro Obregón"
          - id: 2
            descripcion: "Azcapotzalco"
          - id: 3
            descripcion: "Benito Juárez"
          - id: 4
            descripcion: "Coyoacán"
          - id: 5
            descripcion: "Cuajimalpa de Morelos"
          - id: 6
            descripcion: "Cuauhtémoc"
          - id: 7
            descripcion: "Gustavo A. Madero"
          - id: 8
            descripcion: "Iztacalco"
          - id: 9
            descripcion: "Iztapalapa"
          - id: 10
            descripcion: "La Magdalena Contreras"
          - id: 11
            descripcion: "Miguel Hidalgo"
          - id: 12
            descripcion: "Milpa Alta"
          - id: 13
            descripcion: "Tlalpan"
          - id: 14
            descripcion: "Tláhuac"
          - id: 15
            descripcion: "Venustiano Carranza"
          - id: 16
            descripcion: "Xochimilco"
  
  municipios:
    type: object
    properties:
      id:
        type: integer
        description: Id del muncipio.
      descripcion:
        type: string
        description: Nombre del municipio.

  error:
    type: object
    properties:
      codigo:
        type: string 
        description: Código del error.        
      mensaje:
        type: string
        description: Descripción del error.        
      folio:
        type: string
        description: Número de folio de la operación.        
      info:
        type: string
        description: Rutas de ayuda para atender el error.        
      detalles:
        type: array
        items:
          type: string
          example: ""
    required:
    - codigo
    - mensaje 
    - folio 
    - info 
    - detalles  

  summary:
    type: object
    properties:
      api-name:
        type: string
        description: API para consulta de catálogos del proceso originación de crédito - préstamos personales (clientes nuevos).
        example: Catálogos v1.
      tipos-identificaciones-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta de tipo de identificación del cliente.
            example: Catálogos de tipos identificaciones.
      dias-pago-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de días de pago.
            example: Catálogo de días de pago.
      motivos-credito-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de motivos.
            example: Catálogos de Motivos.  
      destinos-credito-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de destinos.
            example: Catálogos de destinos.  
      tipos-dispersion-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de tipos de dispersiones.
            example: Catálogos de tipos de dispersiones.   
      tipos-empleos-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de tipos de empleos.
            example: Catálogos de tipos de empleos.       
      ocupaciones-get:
        type: object
        properties:
          displayName:
            type: string
            description: Realiza la consulta del catálogo de Ocupaciones.
            example: Catálogos de Ocupaciones.   
      paises-get:
        type: object
        properties:
          displayName:  
            type: string
            description: Realiza la consulta del catálogo de paises.
            example: Catálogo de paises.                  
      municipios-get:
        type: object
        properties:
          displayName:  
            type: string
            description: Realiza la consulta de municipios por estado.
            example: Catálogo de municipios.       